name: rsna
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.3
  - pandas
  - numpy
  - pydicom
  - tqdm
  - matplotlib
  - pip
  - opencv
  - scikit-learn
  - albumentations
  - keras
  - pip:
    - pandas

